"""Workstream templates imported from the EnFin AVL Requirements Trackers.

Source: the per-product-type Google Sheets maintained by EnFin Team AVL (Jun 2026).
Each sheet is a "Document Category -> Required Document" checklist with a
Required / Optional / Conditional obligation and notes. Items below are
(category, requirement, obligation, notes) and keep the sheet's row order.

These ship as the starter library; everything is editable at /workstreams.
"""

SRC = "https://docs.google.com/spreadsheets/d/{}/edit"

# ---------------------------------------------------------------- PV Module (DC)
PV_MODULE_DC = [
    ("Core Product & Compliance", "Product Datasheet (all DC SKUs: Q.PEAK DUO P-PERC + Q.TRON N-TOPCon)", "Required", ""),
    ("Core Product & Compliance", "Domestic Content package: DCA letter (or non-applicability statement) plus component cost breakdown mapped to Notice 2025-08 safe-harbor table", "Required", "Letter alone is insufficient; must include component-level mapping so EnFin can run and defend the calc"),
    ("Core Product & Compliance", "FEOC / PFE memo: company-ownership level and product-level (cells / wafers / polysilicon country-of-origin) plus MACR calculation", "Required", "Notice 2026-15; module >=40% non-FEOC (2026). Single memo acceptable if it covers all three"),
    ("Core Product & Compliance", "Supplier non-FEOC / PFE certifications (cells / wafers / polysilicon)", "Required", "NEW: Certification Safe Harbor"),
    ("Core Product & Compliance", "Installation & Operations Manual (IOM), current revision", "Required", ""),
    ("Core Product & Compliance", "AVL database check: intake label, model name, SKU/PN validation", "Required", "EnFin internal (Team AVL); both SKU families"),
    ("Factory Quality", "ISO 9001 Certificate", "Required", ""),
    ("Factory Quality", "ISO 14001 Certificate", "Required", ""),
    ("Factory Quality", "ISO 45001 (Occupational Health & Safety)", "Optional", "Recommended"),
    ("Factory Quality", "In-line process quality control (IPQC) documentation", "Required", "NEW: DNV TBL"),
    ("Factory Quality", "Most recent factory audit report", "Required", "NEW"),
    ("Bankability & Financials", "BNEF Tier 1 Listing Proof", "Required", ""),
    ("Bankability & Financials", "DNV PV Module Bankability / Technology Review", "Required", "Interim before beta; final at close (per cell line as needed)"),
    ("3rd Party Reliability & Performance", "PVEL Product Qualification Program (PQP) Scorecard", "Required", "TC, DH, MSS, HSS, PID, UVID, LID+LETID, PAN (per BOM)"),
    ("3rd Party Reliability & Performance", "PVEL Top Performer status (target: all 8 categories)", "Optional", "NEW: stand-out opportunity"),
    ("3rd Party Reliability & Performance", "RETC PV Module Index / Thresher Test report", "Required", "BOM-specific"),
    ("3rd Party Reliability & Performance", "RETC Overall Highest Achiever (independent inventory sampling)", "Optional", "NEW: stand-out opportunity"),
    ("3rd Party Reliability & Performance", "Extended Reliability Test (ERT) Report (RETC, etc.)", "Required", ""),
    ("3rd Party Reliability & Performance", "3rd Party Witness Testing Program details", "Required", ""),
    ("3rd Party Reliability & Performance", "IEC 62804 / PID resistance test", "Conditional", "PVEL PQP-subsumed or RETC Thresher"),
    ("3rd Party Reliability & Performance", "LID / LeTID characterization", "Conditional", "PVEL PQP-subsumed or RETC Thresher"),
    ("3rd Party Reliability & Performance", "UVID (UV-induced degradation) test", "Conditional", "PVEL PQP-subsumed or RETC Thresher"),
    ("3rd Party Reliability & Performance", "Hail durability test (RETC / VDE, >= 25 mm / >= 20 J)", "Required", "NEW: TX hail exposure"),
    ("3rd Party Reliability & Performance", "Reliability protocols (MTBF, FMEA, SPC)", "Required", ""),
    ("3rd Party Reliability & Performance", "Field RMA / return-rate data", "Required", "NEW"),
    ("Beta & Field Validation", "Beta test protocol (sample size, duration, sites, success criteria / KPIs)", "Required", "NEW: AVL approval gate"),
    ("Beta & Field Validation", "Beta unit deployment & serial-number tracking log", "Required", "NEW"),
    ("Beta & Field Validation", "Beta test results report + AVL gate sign-off", "Required", "NEW"),
    ("Beta & Field Validation", "Field test review: measured PAN / energy yield & degradation vs datasheet", "Required", "NEW: N-TOPCon 0.33%/yr warranted; compare P-PERC vs N-TOPCon"),
    ("Beta & Field Validation", "Field monitoring / telemetry review", "Required", "NEW"),
    ("Beta & Field Validation", "Beta-cohort RMA / failure analysis (root cause + CAPA)", "Required", "NEW"),
    ("Software & API", "NREL SAM (.PAN) file: 3rd-party measured PAN", "Required", "Per cell technology"),
    ("Software & API", "PVSYST file", "Required", "Per cell technology"),
    ("Software & API", "Aurora / OpenSolar / etc. model files", "Required", ""),
    ("Certification", "UL 61730-1 / -2 (PV module safety)", "Required", ""),
    ("Certification", "IEC 61730 (PV module safety qualification)", "Conditional", "UL 61730-1/-2 is the binding US cert (harmonized); IEC version for global bankability only"),
    ("Certification", "IEC 61215 (design qualification & type approval)", "Required", ""),
    ("Certification", "UL 790 / fire classification (Class A)", "Conditional", "Within UL 61730-2; standalone only for system-level Class A"),
    ("Certification", "IEC 61701 (salt-mist corrosion)", "Optional", "Coastal deployments"),
    ("Certification", "IEC 62716 (ammonia corrosion)", "Optional", "Agricultural deployments"),
    ("Certification", "CEC listing (module)", "Required", ""),
    ("Company & Legal", "Vendor profile: legal name", "Required", ""),
    ("Company & Legal", "Vendor profile: address", "Required", ""),
    ("Company & Legal", "Vendor profile: all physical locations", "Required", ""),
    ("Company & Legal", "Vendor profile: website URL", "Required", ""),
    ("Company & Legal", "Vendor profile: years in business", "Required", ""),
    ("Company & Legal", "Vendor profile: annual revenue", "Required", ""),
    ("Company & Legal", "Listed States of Incorporation & Articles of Incorporation", "Required", ""),
    ("Company & Legal", "Affiliated and parent companies / cap table summary", "Required", ""),
    ("Company & Legal", "Officer / Director list and key personnel (KYC)", "Required", ""),
    ("Company & Legal", "Training (PIs) / customer service programs available?", "Required", ""),
    ("Compliance & Risk", "Specialized / compliance certifications or licenses (company-level)", "Required", ""),
    ("Compliance & Risk", "Regulatory compliance (industry-specific)", "Required", ""),
    ("Compliance & Risk", "FEOC / PFE @ company-ownership OR product-level", "Required", "See Core Product & Compliance"),
    ("Compliance & Risk", "DCA requirements: are DCA products available?", "Required", ""),
    ("Compliance & Risk", "No history of major legal / ethical violations (attestation)", "Required", ""),
    ("Compliance & Risk", "Pending or threatened litigation disclosure", "Required", "Standard for tax equity"),
    ("Compliance & Risk", "Vendor / Supplier Code of Conduct", "Required", "Tessa action"),
    ("Compliance & Risk", "Data Security Policy (company-level)", "Required", ""),
    ("Supply Chain & Logistics", "Ability to handle fluctuations in demand", "Required", ""),
    ("Supply Chain & Logistics", "Ability to scale production", "Required", ""),
    ("Supply Chain & Logistics", "Traceability procedures in place", "Required", ""),
    ("Supply Chain & Logistics", "RMA process provided", "Required", ""),
    ("Supply Chain & Logistics", "ANSI/SEIA 101 traceability protocol attestation", "Required", "NEW"),
    ("Supply Chain & Logistics", "UFLPA compliance attestation", "Required", "NEW: critical for PV polysilicon traceability"),
    ("Supply Chain & Logistics", "Third-party UFLPA audit reports", "Required", "Tessa action"),
    ("Supply Chain & Logistics", "Third-party manufacturing facility inspection reports", "Required", "Tessa action"),
    ("Supply Chain & Logistics", "Sustainability strategy / EPR statement", "Required", "RCRA & Universal Waste Rule"),
    ("Supply Chain & Logistics", "Recycling policy (RCRA / Universal Waste Rule compliant)", "Required", ""),
    ("Supply Chain & Logistics", "OSHA-aligned safety policy", "Required", "Tessa action"),
    ("Financial", "Credit check / annual report (audited financials if private)", "Required", ""),
    ("Financial", "Significant deals (mergers / acquisitions / spin-offs)", "Required", ""),
    ("Financial", "Insolvency / business continuity provisions", "Required", ""),
    ("Financial", "Technology / source-code escrow availability", "Optional", "Tail-risk for 25-yr tax equity life"),
    ("Bankability", "Parent Co. backing report", "Required", "Hanwha Qcells"),
    ("Insurance", "Certificate of Insurance (COI): additional insured naming (EnFin / Qcells / lessees)", "Required", "NEW: Tessa action"),
    ("Insurance", "Product liability insurance (policy & limits)", "Required", ""),
    ("Insurance", "General liability insurance (policy & limits)", "Required", ""),
    ("Insurance", "Professional liability / E&O insurance", "Optional", ""),
    ("Warranty & Service", "Limited Warranty: full terms & conditions (product + power)", "Required", ""),
    ("Warranty & Service", "Module power + product warranty vs degradation curve", "Required", "NEW: P-PERC and N-TOPCon warranted curves (N-TOPCon 0.33%/yr)"),
    ("Warranty & Service", "Warranty labor coverage clarification (parts vs parts+labor)", "Required", ""),
    ("Warranty & Service", "Out-of-warranty service price schedule", "Required", "For OPEX modeling"),
    ("Warranty & Service", "Warranty financial backstop / wrap (insurance carrier)", "Required", "NEW: long-warranty counterparty risk"),
]


# ---------------------------------------------------------------- AC Module
# The P-PERC and N-TOPCon sheets carry the same checklist; only a few notes
# differ by cell technology, applied as overrides below.
AC_MODULE = [
    ("Core Product & Compliance", "Product Datasheet (specific SKUs)", "Required", "Module + integrated microinverter datasheets"),
    ("Core Product & Compliance", "AC system datasheet (module + microinverter as one UL-listed unit)", "Required", ""),
    ("Core Product & Compliance", "Domestic Content package: DCA letter (or non-applicability statement) plus component cost breakdown mapped to Notice 2025-08 safe-harbor table", "Required", "Letter alone is insufficient; must include component-level mapping so EnFin can run and defend the calc"),
    ("Core Product & Compliance", "FEOC / PFE memo: company-ownership level and product-level (cells / wafers / polysilicon country-of-origin) plus MACR calculation", "Required", "Notice 2026-15; module >=40% non-FEOC (2026). Single memo acceptable if it covers all three"),
    ("Core Product & Compliance", "Supplier non-FEOC / PFE certifications (cells, wafers, inverter)", "Required", "NEW - Certification Safe Harbor"),
    ("Core Product & Compliance", "Installation & Operations Manual (IOM)", "Required", ""),
    ("Core Product & Compliance", "AVL database check; intake label, model name, SKU/PN validation", "Required", "Validate via Salesforce & Aurora (alias check)"),
    ("Core Product & Compliance", "Microinverter firmware version + update / cybersecurity policy", "Required", "NEW"),
    ("Factory Quality", "ISO 9001 Certificate (module factory)", "Required", ""),
    ("Factory Quality", "ISO 14001 Certificate (module factory)", "Required", ""),
    ("Factory Quality", "ISO 45001 (Occupational Health & Safety)", "Optional", "Recommended"),
    ("Factory Quality", "Microinverter factory ISO 9001", "Required", "NEW - AC module = two supply chains to qualify"),
    ("Factory Quality", "In-line process quality control (IPQC) documentation", "Required", "NEW - DNV TBL: in-line QC dimension"),
    ("Factory Quality", "Most recent factory audit report", "Required", "NEW - DNV / IE manufacturing audit"),
    ("3rd Party Reliability", "Reliability protocols (MTBF / FMEA) - module & microinverter", "Required", ""),
    ("3rd Party Reliability", "RETC Thresher Test report (BOM-specific)", "Required", "NEW - beyond-cert bankability; must tie to AVL'd BOM"),
    ("3rd Party Reliability", "PVEL PQP report + Scorecard Top Performer status", "Required", "NEW - TC, DH, MSS, HSS, PID, UVID, LID+LETID, PAN"),
    ("3rd Party Reliability", "DNV Bankability / Technology Review Report", "Required", "Interim before beta; final at close"),
    ("3rd Party Reliability", "Microinverter HALT/HASS + power-cycling + MTBF/FIT", "Required", "NEW - AC-module specific reliability"),
    ("3rd Party Reliability", "Hail durability (RETC Hail Resiliency Curve, >=20 J)", "Optional", "NEW - TX hail exposure (EnFin footprint)"),
    ("3rd Party Reliability", "Long-term field pilot / NRTL study data", "Optional", ""),
    ("3rd Party Reliability", "Field RMA / return-rate data (12-24 mo)", "Required", "NEW - financier requirement"),
    ("Beta & Field Validation", "Beta test protocol (sample size, duration, sites, success criteria / KPIs)", "Required", ""),
    ("Beta & Field Validation", "Beta unit deployment & serial-number tracking log", "Required", ""),
    ("Beta & Field Validation", "Beta test results report + AVL gate sign-off", "Required", ""),
    ("Beta & Field Validation", "Field test review: measured performance vs datasheet (PAN / energy-yield correlation)", "Required", ""),
    ("Beta & Field Validation", "Field monitoring data review (microinverter telemetry, fault / derate rates)", "Required", ""),
    ("Beta & Field Validation", "Beta-cohort RMA / failure analysis (root cause + CAPA)", "Required", ""),
    ("Software & API", "PVsyst file incl. PAN file", "Required", "NEW - PAN energy-yield modeling for IE"),
    ("Software & API", "NREL SAM file", "Optional", ""),
    ("Software & API", "Aurora / OpenSolar / SolarGraf model files", "Optional", ""),
    ("Software & API", "API documentation (monitoring / integration)", "Required", ""),
    ("Software & API", "Cybersecurity / data-security attestation (monitoring platform)", "Required", "NEW"),
    ("Module Certification", "IEC 61215 (Design Qualification & Type Approval)", "Required", ""),
    ("Module Certification", "IEC 61730-1 / -2 (PV Module Safety Qualification)", "Conditional", "Harmonized with UL 61730; non-US only"),
    ("Module Certification", "UL 61730 / UL 1703", "Required", "UL 1703 legacy listings acceptable; no new certs since 2020 transition"),
    ("Module Certification", "UL 790 / ASTM E108 Fire Classification (Class A)", "Conditional", "Within UL 61730-2; standalone only for system-level Class A"),
    ("Module Certification", "IEC 62804 (PID Resistance)", "Conditional", "PVEL PQP-subsumed or RETC Thresher"),
    ("Module Certification", "LID / LeTID characterization", "Conditional", "PVEL PQP-subsumed or RETC Thresher"),
    ("Module Certification", "UV-induced degradation (UVID) test", "Conditional", "PVEL PQP-subsumed or RETC Thresher"),
    ("Module Certification", "IEC 61853-1/-2 (Energy Rating; temp/irradiance, PAN)", "Optional", "Recommended"),
    ("Module Certification", "IEC 61701 (Salt Mist) / IEC 62716 (Ammonia)", "Optional", "Required for coastal / agrivoltaic siting"),
    ("Module Certification", "IEC 60068-2-68 (Sand & Dust)", "Optional", ""),
    ("Module Certification", "IEC TS 63126 (high-temperature operation qualification)", "Optional", ""),
    ("Module Certification", "UL 3741 (PV Hazard Control System)", "Conditional", "If module-level rapid shutdown is claimed"),
    ("Inverter / AC-Side", "UL 1741 SB (+ CRD for IEEE 1547-2018)", "Required", ""),
    ("Inverter / AC-Side", "IEEE 1547 / 1547.1 (Interconnection + test)", "Conditional", "Evidenced by UL 1741 SB"),
    ("Inverter / AC-Side", "UL 62109-1 / -2 (Inverter Safety)", "Conditional", "Covered by UL 1741 unit listing of the AC module"),
    ("Inverter / AC-Side", "CEC listing (module + inverter on CEC lists)", "Required", "NEW - CA market gate"),
    ("Inverter / AC-Side", "FCC Part 15 (EMC)", "Required", ""),
    ("Inverter / AC-Side", "NEC 690.12 Rapid Shutdown compliance", "Conditional", "Evidenced within 1741 listing"),
    ("Inverter / AC-Side", "UL 1998 (Software in Programmable Components)", "Conditional", "In UL 1741 test report"),
    ("Inverter / AC-Side", "Utility / grid-code approval (Rule 21, etc.)", "Required", ""),
    ("Company & Legal", "Vendor profile: legal name", "Required", ""),
    ("Company & Legal", "Vendor profile: address", "Required", ""),
    ("Company & Legal", "Vendor profile: all physical locations", "Required", ""),
    ("Company & Legal", "Vendor profile: website URL", "Required", ""),
    ("Company & Legal", "Vendor profile: years in business", "Required", ""),
    ("Company & Legal", "Vendor profile: annual revenue", "Required", ""),
    ("Company & Legal", "Listed States of Incorporation & Articles of Incorporation", "Required", ""),
    ("Company & Legal", "Affiliated and parent companies", "Required", "Hanwha / Qcells + microinverter OEM"),
    ("Company & Legal", "Training (PIs) / customer service programs available?", "Required", ""),
    ("Compliance & Risk", "Specialized / compliance certifications or licenses (company-level)", "Required", ""),
    ("Compliance & Risk", "Regulatory compliance (industry-specific)", "Required", ""),
    ("Compliance & Risk", "FEOC / PFE @ company-ownership OR product-level", "Required", ""),
    ("Compliance & Risk", "DCA requirements: are DCA products available?", "Required", ""),
    ("Compliance & Risk", "No history of major legal / ethical violations", "Required", ""),
    ("Compliance & Risk", "Data Security Policy", "Required", ""),
    ("Compliance & Risk", "Cybersecurity attestation (connected-device / monitoring)", "Required", "NEW"),
    ("Supply Chain & Logistics", "Ability to handle fluctuations in demand", "Required", ""),
    ("Supply Chain & Logistics", "Ability to scale production", "Required", ""),
    ("Supply Chain & Logistics", "Traceability procedures in place (serialization / anti-counterfeit)", "Required", "NEW emphasis"),
    ("Supply Chain & Logistics", "RMA process provided", "Required", ""),
    ("Financial / Bankability", "Credit check / annual report (audited financials if private)", "Required", ""),
    ("Financial / Bankability", "Parent Co. (Hanwha Qcells) backing report", "Required", ""),
    ("Financial / Bankability", "Significant deals (mergers / acquisitions / spin-offs)", "Required", ""),
    ("Financial / Bankability", "Warranty terms + warranty-insurance backing", "Required", "NEW"),
    ("Financial / Bankability", "Product & performance warranty vs degradation curve", "Required", "NEW - map warranted degradation curve to financier yield model"),
]

# requirement -> replacement note, per cell technology
AC_PPERC_NOTES = {
    "Product Datasheet (specific SKUs)": "Q.PEAK DUO ML AC module (P-PERC) + integrated Q.MI microinverter datasheets",
    "Product & performance warranty vs degradation curve": "NEW - map P-PERC degradation curve (yr-1 + linear) to financier yield model",
}
AC_NTOPCON_NOTES = {
    "Product Datasheet (specific SKUs)": "Q.TRON AC Module datasheet (N-TOPCon) + integrated microinverter",
    "Product & performance warranty vs degradation curve": "NEW - N-TOPCon 0.33%/yr warranted degradation mapped to financier yield model",
}

def _with_notes(items, overrides):
    return [(c, r, o, overrides.get(r, n)) for c, r, o, n in items]


# ---------------------------------------------------------------- Inverter / Microinverter
INVERTER = [
    ("Core Product & Compliance", "Product Datasheet (specific SKUs)", "Required", ""),
    ("Core Product & Compliance", "Domestic Content package: DCA letter (or non-applicability statement) plus component cost breakdown mapped to Notice 2025-08 safe-harbor table", "Required", "Letter alone is insufficient; must include component-level mapping so EnFin can run and defend the calc"),
    ("Core Product & Compliance", "FEOC / PFE memo: company-ownership level and product-level (country-of-origin) plus MACR calculation", "Required", "Notice 2026-15. Single memo acceptable if it covers all three"),
    ("Core Product & Compliance", "Supplier non-FEOC / PFE certifications (semiconductors, PCBA, enclosure)", "Required", "NEW: Certification Safe Harbor"),
    ("Core Product & Compliance", "Installation & Operations Manual (IOM), current revision", "Required", ""),
    ("Core Product & Compliance", "Firmware version + cybersecurity update / patch policy", "Required", "NEW"),
    ("Core Product & Compliance", "AVL database check: intake label, model name, SKU/PN validation", "Required", "EnFin internal (Team AVL)"),
    ("Factory Quality", "ISO 9001 Certificate", "Required", ""),
    ("Factory Quality", "ISO 14001 Certificate", "Required", ""),
    ("Factory Quality", "ISO 45001 (Occupational Health & Safety)", "Optional", "Recommended"),
    ("Factory Quality", "In-line process quality control (IPQC) documentation", "Required", "NEW: DNV TBL"),
    ("Factory Quality", "Most recent factory audit report", "Required", "NEW"),
    ("3rd Party Reliability & Performance", "3rd Party Extended Reliability Test Report (PVEL / Intertek / RETC)", "Required", ""),
    ("3rd Party Reliability & Performance", "PVEL PV Inverter scorecard / reliability data", "Optional", "NEW: stand-out opportunity"),
    ("3rd Party Reliability & Performance", "Reliability protocols (MTBF, FMEA, FIT, SPC)", "Required", ""),
    ("3rd Party Reliability & Performance", "Accelerated life test data (Telcordia SR-332; damp heat, thermal cycling)", "Required", "NEW: power-electronics reliability methodology"),
    ("3rd Party Reliability & Performance", "HALT / HASS reports", "Required", "NEW"),
    ("3rd Party Reliability & Performance", "3rd Party IE / Bankability Report (DNV / B&V / Leidos)", "Required", ""),
    ("3rd Party Reliability & Performance", "DNV technology / bankability review", "Required", "Interim before beta; final at close"),
    ("3rd Party Reliability & Performance", "CEC weighted efficiency + listing on CEC Approved Inverter List", "Required", ""),
    ("3rd Party Reliability & Performance", "Field RMA / return-rate data", "Required", "NEW"),
    ("Beta & Field Validation", "Beta test protocol (sample size, duration, sites, success criteria / KPIs)", "Required", "NEW: AVL approval gate"),
    ("Beta & Field Validation", "Beta unit deployment & serial-number tracking log", "Required", "NEW"),
    ("Beta & Field Validation", "Beta test results report + AVL gate sign-off", "Required", "NEW"),
    ("Beta & Field Validation", "Field review: measured efficiency / MPPT / energy yield vs datasheet", "Required", "NEW"),
    ("Beta & Field Validation", "Field monitoring / telemetry review (fault codes, thermal derating)", "Required", "NEW"),
    ("Beta & Field Validation", "Beta-cohort RMA / failure analysis (root cause + CAPA)", "Required", "NEW"),
    ("Software & API", "Performance & loss factors (3rd-party models)", "Required", ""),
    ("Software & API", "NREL SAM (.OND) file: 3rd-party tested OND for inverter modeling", "Required", ""),
    ("Software & API", "PVSYST file", "Required", ""),
    ("Software & API", "Aurora / OpenSolar / etc. model files", "Required", ""),
    ("Software & API", "API documentation (monitoring / integration / access)", "Required", ""),
    ("Software & API", "Rapid-shutdown / module-level control spec (MLPE)", "Required", "Where applicable (MI / power optimizers)"),
    ("Software & API", "Cybersecurity / data-security attestation (cloud / monitoring)", "Required", "NEW"),
    ("Certification", "UL 1741-SB", "Required", "UL 1741 SB (grid-support, IEEE 1547-2018)"),
    ("Certification", "IEEE 1547 / 1547.1 (interconnection standard)", "Conditional", "Evidenced by UL 1741 SB"),
    ("Certification", "IEC 62109-1 / -2 (inverter safety)", "Conditional", "Absorbed by UL 1741 3rd Ed; non-US only"),
    ("Certification", "IEC 61683 (efficiency)", "Conditional", "CEC weighted efficiency is binding US test"),
    ("Certification", "UL 1699B (PV arc-fault protection)", "Conditional", "DC circuits >=80V per NEC 690.11; MI/ACM exempt"),
    ("Certification", "Rapid shutdown: NEC 690.12 / UL PVRSE / SunSpec", "Conditional", "Within UL 1741 scope where inverter/MLPE provides RSD"),
    ("Certification", "IEC 61215 & IEC 63209 (DH & TC to 85C)", "Required", "For MI / ACM rooftop BOMT"),
    ("Certification", "IEC 62116 (anti-islanding)", "Conditional", "Tested under UL 1741 SB"),
    ("Certification", "FCC Part 15 Class B (emissions)", "Required", "Wireless / comms modules"),
    ("Certification", "CEC listing (inverter)", "Required", ""),
    ("Certification", "UL 2900 / IEC 62443 (cybersecurity)", "Optional", "NEW: increasingly a financier gate"),
    ("Company & Legal", "Vendor profile: legal name", "Required", ""),
    ("Company & Legal", "Vendor profile: address", "Required", ""),
    ("Company & Legal", "Vendor profile: all physical locations", "Required", ""),
    ("Company & Legal", "Vendor profile: website URL", "Required", ""),
    ("Company & Legal", "Vendor profile: years in business", "Required", ""),
    ("Company & Legal", "Vendor profile: annual revenue", "Required", ""),
    ("Company & Legal", "Listed States of Incorporation & Articles of Incorporation", "Required", ""),
    ("Company & Legal", "Affiliated and parent companies / cap table summary", "Required", ""),
    ("Company & Legal", "Officer / Director list and key personnel (KYC)", "Required", ""),
    ("Company & Legal", "Training (PIs) / customer service programs available?", "Required", ""),
    ("Compliance & Risk", "Specialized / compliance certifications or licenses (company-level)", "Required", ""),
    ("Compliance & Risk", "Regulatory compliance (industry-specific)", "Required", ""),
    ("Compliance & Risk", "FEOC / PFE @ company-ownership OR product-level", "Required", "See Core Product & Compliance"),
    ("Compliance & Risk", "DCA requirements: are DCA products available?", "Required", ""),
    ("Compliance & Risk", "No history of major legal / ethical violations (attestation)", "Required", ""),
    ("Compliance & Risk", "Pending or threatened litigation disclosure", "Required", "Standard for tax equity"),
    ("Compliance & Risk", "Vendor / Supplier Code of Conduct", "Required", "Tessa action"),
    ("Compliance & Risk", "Data Security Policy (company-level)", "Required", ""),
    ("Supply Chain & Logistics", "Ability to handle fluctuations in demand", "Required", ""),
    ("Supply Chain & Logistics", "Ability to scale production", "Required", ""),
    ("Supply Chain & Logistics", "Traceability procedures in place", "Required", ""),
    ("Supply Chain & Logistics", "RMA process provided", "Required", ""),
    ("Supply Chain & Logistics", "ANSI/SEIA 101 traceability protocol attestation", "Required", "NEW"),
    ("Supply Chain & Logistics", "UFLPA compliance attestation", "Required", "NEW: increasingly required by tax equity"),
    ("Supply Chain & Logistics", "Third-party UFLPA audit reports", "Required", "Tessa action"),
    ("Supply Chain & Logistics", "Third-party manufacturing facility inspection reports", "Required", "Tessa action"),
    ("Supply Chain & Logistics", "Sustainability strategy / EPR statement", "Required", "RCRA & Universal Waste Rule"),
    ("Supply Chain & Logistics", "Recycling policy (RCRA / Universal Waste Rule compliant)", "Required", ""),
    ("Supply Chain & Logistics", "OSHA-aligned safety policy", "Required", "Tessa action"),
    ("Financial", "Credit check / annual report (audited financials if private)", "Required", ""),
    ("Financial", "Significant deals (mergers / acquisitions / spin-offs)", "Required", ""),
    ("Financial", "Insolvency / business continuity provisions", "Required", ""),
    ("Financial", "Technology / source-code escrow availability", "Optional", "Tail-risk for 25-yr tax equity life"),
    ("Bankability", "Parent Co. backing report", "Required", ""),
    ("Insurance", "Certificate of Insurance (COI): additional insured naming (EnFin / Qcells / lessees)", "Required", "NEW: Tessa action"),
    ("Insurance", "Product liability insurance (policy & limits)", "Required", ""),
    ("Insurance", "General liability insurance (policy & limits)", "Required", ""),
    ("Insurance", "Professional liability / E&O insurance", "Optional", ""),
    ("Insurance", "Cyber liability insurance (policy & limits)", "Required", "Connected-device exposure"),
    ("Warranty & Service", "Limited Warranty (USA): full terms & conditions", "Required", ""),
    ("Warranty & Service", "Warranty labor coverage clarification (parts vs parts+labor)", "Required", ""),
    ("Warranty & Service", "Out-of-warranty service price schedule", "Required", "For OPEX modeling"),
    ("Warranty & Service", "Warranty financial backstop / wrap (insurance carrier)", "Required", "NEW: long-warranty counterparty risk"),
]


# ---------------------------------------------------------------- ESS / BESS (Gen4)
ESS = [
    ("Core Product & Compliance", "Product Datasheet (specific SKUs)", "Required", "Gen4 ESS datasheet"),
    ("Core Product & Compliance", "Domestic Content package: DCA letter (or non-applicability statement) plus component cost breakdown mapped to Notice 2025-08 safe-harbor table", "Required", "Letter alone is insufficient; must include component-level mapping so EnFin can run and defend the calc"),
    ("Core Product & Compliance", "FEOC / PFE memo: company-ownership level and product-level (cells / country-of-origin) plus MACR calculation", "Required", "Notice 2026-15; storage >=55% non-FEOC (2026). Single memo acceptable if it covers all three"),
    ("Core Product & Compliance", "Supplier non-FEOC / PFE certifications (cells / modules)", "Required", "NEW - Certification Safe Harbor"),
    ("Core Product & Compliance", "Installation & Operations Manual (IOM)", "Required", ""),
    ("Core Product & Compliance", "AVL database check; intake label, model name, SKU/PN validation", "Required", "Salesforce & Aurora"),
    ("Core Product & Compliance", "Firmware / BMS software version + cybersecurity update policy", "Required", "NEW"),
    ("Factory Quality", "ISO 9001 Certificate", "Required", ""),
    ("Factory Quality", "ISO 14001 Certificate", "Required", ""),
    ("Factory Quality", "ISO 45001 (Occupational Health & Safety)", "Optional", "Recommended"),
    ("Factory Quality", "In-line process quality control (IPQC) documentation", "Required", "NEW - DNV TBL"),
    ("Factory Quality", "Most recent factory audit report", "Required", "NEW"),
    ("3rd Party Reliability", "RETC 3rd party testing (or equivalent)", "Required", ""),
    ("3rd Party Reliability", "DNV ESS Technology Review & Reliability protocols (MTBF, FMEA)", "Required", "Interim before beta; final at close"),
    ("3rd Party Reliability", "Cycle-life / capacity-retention test data", "Required", ""),
    ("3rd Party Reliability", "Round-trip efficiency test data", "Required", ""),
    ("3rd Party Reliability", "Long-term field pilot / NRTL study data", "Optional", ""),
    ("3rd Party Reliability", "Field RMA / return-rate data", "Required", ""),
    ("Beta & Field Validation", "Beta test protocol (sample size, duration, sites, success criteria / KPIs)", "Required", ""),
    ("Beta & Field Validation", "Beta unit deployment & serial-number tracking log", "Required", ""),
    ("Beta & Field Validation", "Beta test results report + AVL gate sign-off", "Required", ""),
    ("Beta & Field Validation", "Field test review: measured round-trip efficiency & capacity retention vs spec", "Required", ""),
    ("Beta & Field Validation", "Field monitoring / BMS data review (fault, thermal, SOC/SOH trends)", "Required", ""),
    ("Beta & Field Validation", "Beta-cohort RMA / failure analysis (root cause + CAPA)", "Required", ""),
    ("Software & API", "NREL SAM / PVSYST file", "Optional", ""),
    ("Software & API", "Aurora / OpenSolar model files", "Optional", ""),
    ("Software & API", "API documentation", "Required", ""),
    ("Software & API", "Cybersecurity / data-security attestation (cloud / monitoring)", "Required", "NEW"),
    ("Certification", "UL 9540 (ESS Safety; ed. referenced by IFC 2024 / NFPA 855-2026)", "Required", "System-level listing; incorporates UL 1973 (battery) and UL 1741 (PCS) by reference"),
    ("Certification", "UL 9540A 6th Ed.: cell and module level test reports", "Required", "UPDATED: Ed. 6 published 13-Mar-2026. Confirm reports are run to Ed. 6, not Ed. 5"),
    ("Certification", "UL 9540A: Unit Level Test (residential BESS)", "Required", "Terminal test for residential. Substantiates separation / reduced spacing; claimed spacing must match the tested configuration and appear in the UL 9540 listing and IOM"),
    ("Certification", "UL 9540A: Installation / Large-Scale Fire Test (Section 10)", "Conditional", "Non-residential only. Ed. 6 Section 10 aligned to NFPA 855-2026 Annex G.11"),
    ("Certification", "UL 9540A Annex C: large-scale deflagration test (enclosure)", "Conditional", "NEW in Ed. 6. Applies where required by NFPA 855 / AHJ"),
    ("Certification", "UL 1973 (Battery Safety)", "Conditional", "Battery evaluated within UL 9540 listing"),
    ("Certification", "UL 62109 / IEC 62109 (PCS / inverter safety)", "Conditional", "PCS covered by UL 1741 via UL 9540"),
    ("Certification", "UL 1741 SB (Grid-Support Functions)", "Conditional", "Grid-interactive PCS, standalone or evidenced in UL 9540"),
    ("Certification", "IEEE 1547 / 1547.1 (Interconnection Standard)", "Conditional", "Evidenced by UL 1741 SB"),
    ("Certification", "IEC 62116 (Anti-Islanding)", "Conditional", "Tested under UL 1741 SB / IEEE 1547.1"),
    ("Certification", "UL 2941 & UL 2900-1 / IEC 62443 (Cybersecurity)", "Conditional", "NEW - increasingly a financier gate, confirmed by DNV"),
    ("Certification", "NFPA 855 (2026)-compliant IOM + IFC 2024 / IRC alignment", "Required", "UPDATED"),
    ("Company & Legal", "Vendor profile: legal name", "Required", ""),
    ("Company & Legal", "Vendor profile: address", "Required", ""),
    ("Company & Legal", "Vendor profile: all physical locations", "Required", ""),
    ("Company & Legal", "Vendor profile: website URL", "Required", ""),
    ("Company & Legal", "Vendor profile: years in business", "Required", ""),
    ("Company & Legal", "Vendor profile: annual revenue", "Required", ""),
    ("Company & Legal", "Listed States of Incorporation & Articles of Incorporation", "Required", ""),
    ("Company & Legal", "Affiliated and parent companies", "Required", "Hanwha / Qcells + cell supplier"),
    ("Company & Legal", "Training (PIs) / customer service programs available?", "Required", ""),
    ("Compliance & Risk", "Specialized / compliance certifications or licenses (company-level)", "Required", ""),
    ("Compliance & Risk", "Regulatory compliance (industry-specific)", "Required", ""),
    ("Compliance & Risk", "FEOC / PFE @ company-ownership OR product-level", "Required", ""),
    ("Compliance & Risk", "DCA requirements: are DCA products available?", "Required", ""),
    ("Compliance & Risk", "No history of major legal / ethical violations", "Required", ""),
    ("Compliance & Risk", "Data Security Policy", "Required", ""),
    ("Compliance & Risk", "Cybersecurity attestation (connected-device / cloud)", "Required", "NEW"),
    ("Supply Chain & Logistics", "Ability to handle fluctuations in demand", "Required", ""),
    ("Supply Chain & Logistics", "Ability to scale production", "Required", ""),
    ("Supply Chain & Logistics", "Traceability procedures in place (serialization / anti-counterfeit)", "Required", "NEW emphasis"),
    ("Supply Chain & Logistics", "RMA process provided", "Required", ""),
    ("Financial / Bankability", "Credit check / annual report (audited financials if private)", "Required", ""),
    ("Financial / Bankability", "Parent Co. (Hanwha Qcells) backing report", "Required", ""),
    ("Financial / Bankability", "Significant deals (mergers / acquisitions / spin-offs)", "Required", ""),
    ("Financial / Bankability", "Warranty terms + warranty-insurance backing", "Required", "NEW"),
    ("Financial / Bankability", "Capacity / throughput warranty vs retention curve", "Required", "NEW"),
]


# ---------------------------------------------------------------- Smart Panel (SPAN)
SMART_PANEL = [
    ("Core Product & Compliance", "Product Datasheet (all SKUs)", "Required", "Q-Ref: Q27"),
    ("Core Product & Compliance", "Domestic Content package: DCA letter (or non-applicability statement) plus component cost breakdown mapped to Notice 2025-08 safe-harbor table", "Required", "Letter alone is insufficient; must include component-level mapping so EnFin can run and defend the calc"),
    ("Core Product & Compliance", "FEOC / PFE memo: company-ownership level and product-level (country-of-origin) plus MACR calculation", "Required", "Notice 2026-15. Single memo acceptable if it covers all three"),
    ("Core Product & Compliance", "Supplier non-FEOC / PFE certifications (sub-components)", "Required", "NEW: Certification Safe Harbor"),
    ("Core Product & Compliance", "Installation & Operations Manual (IOM), current revision", "Required", "Q-Ref: Q23, Q24 (confirm latest revision)"),
    ("Core Product & Compliance", "Firmware version + cybersecurity update / patch policy", "Required", "NEW"),
    ("Core Product & Compliance", "AVL database check: intake label, model name, SKU/PN validation", "Required", "EnFin internal (Team AVL)"),
    ("Core Product & Compliance", "DNV Technology Review (current issue)", "Required", ""),
    ("Core Product & Compliance", "Section 48E Qualification Memorandum (outside counsel)", "Required", "Q-Ref: Q1 (need reliance-letter upgrade)"),
    ("Factory Quality", "ISO 9001:2015 Certificate (contract manufacturer)", "Required", "Q-Ref: Q19 (DNV did NOT review 3.7.1)"),
    ("Factory Quality", "ISO 14001 Certificate (contract manufacturer)", "Required", "Q-Ref: Q19 (DNV did NOT review 3.7.1)"),
    ("Factory Quality", "Supplier Handbook / Supplier Audit Report", "Required", "Q-Ref: Q19 (obtain copy)"),
    ("Factory Quality", "In-line process quality control (IPQC) documentation", "Required", "NEW: DNV TBL"),
    ("Factory Quality", "Most recent factory audit report", "Required", "NEW"),
    ("3rd Party Reliability & Performance", "Reliability protocols (MTBF, FMEA)", "Required", "Q-Ref: Q11, Q15 (component-level Weibull + FMEA)"),
    ("3rd Party Reliability & Performance", "Long-term Field Pilot / NRTL Study Data", "Optional", "Q-Ref: Q11 (field data publication timeline)"),
    ("3rd Party Reliability & Performance", "DVT test reports (HTHE, HTOE, PTCE, HF)", "Required", "Q-Ref: Q13 (obtain primary source)"),
    ("3rd Party Reliability & Performance", "UV exposure test data (ASTM G155)", "Optional", "Q-Ref: Q14"),
    ("3rd Party Reliability & Performance", "Field RMA / return-rate data", "Required", "NEW"),
    ("Beta & Field Validation", "Beta test protocol (sample size, duration, sites, success criteria / KPIs)", "Required", "NEW: AVL approval gate"),
    ("Beta & Field Validation", "Beta unit deployment & serial-number tracking log", "Required", "NEW"),
    ("Beta & Field Validation", "Beta test results report + AVL gate sign-off", "Required", "NEW"),
    ("Beta & Field Validation", "Field review: load-management / circuit-telemetry performance vs spec", "Required", "NEW"),
    ("Beta & Field Validation", "Field monitoring review (fault codes, thermal, connectivity uptime)", "Required", "NEW"),
    ("Beta & Field Validation", "Beta-cohort RMA / failure analysis (root cause + CAPA)", "Required", "NEW"),
    ("Software & API", "API Documentation (integration / access)", "Required", "Q-Ref: Q37, Q38 (smart-home + battery integration, default execution, VPP)"),
    ("Software & API", "App / UI Documentation and Privacy Architecture", "Required", "Q-Ref: Q39 (user-facing app + data-flow diagram)"),
    ("Software & API", "Approved Battery / Inverter Integration List with min firmware versions", "Required", "Q-Ref: Q20, Q22"),
    ("Software & API", "Data Rights / Telemetry Ownership Provisions", "Required", "Q-Ref: Q39 (lessee data ownership for circuit-level telemetry)"),
    ("Software & API", "VPP / Grid Services API spec & commercial terms", "Required", "Q-Ref: Q38 (revenue share, dispatch fees, platform tolls)"),
    ("Software & API", "Remote management / default-execution API spec", "Required", "Q-Ref: Q37 (authorization model + lease-default downgrade path)"),
    ("Software & API", "Cybersecurity / data-security attestation (cloud / monitoring)", "Required", "NEW"),
    ("Certification", "UL 67 (Panelboards)", "Required", "Collect NRTL certificate copy"),
    ("Certification", "UL 869A (Reference Standard for Service Equipment)", "Conditional", "Service equipment use only"),
    ("Certification", "UL 916 (Energy Management Equipment)", "Required", "Load-shedding / smart features; collect ATM"),
    ("Certification", "UL 3141 (Power Control System / PCS)", "Required", "Q-Ref: Q17 (critical for 48E power-conditioning classification)"),
    ("Certification", "NEMA Enclosure Rating Certification (e.g., NEMA 3R)", "Required", ""),
    ("Certification", "FCC Part 15 Class B (emissions)", "Required", "Collect test report copy"),
    ("Certification", "UL 489 (Molded-Case Circuit Breakers)", "Conditional", "Component-level; breaker supplier listing satisfies"),
    ("Certification", "UL 508 (Industrial Control Equipment) relay supplier cert", "Conditional", "Component-level supplier cert"),
    ("Certification", "UL 62368-1 (A/V & Comm Tech Safety)", "Required", ""),
    ("Certification", "UL 1998 (Software in Programmable Components)", "Optional", "Validates software reliability / safety"),
    ("Certification", "NEC 2020 / NEC 2023 Compliance Statement", "Required", "Smart load management; NEC 702.4(A)(2)(b)"),
    ("Certification", "UL 2900 (Cyber Security)", "Conditional", "If UL 2941 achieved"),
    ("Certification", "UL 2941 (DER Cyber Security)", "Optional", "Q-Ref: Q18"),
    ("Certification", "SunSpec Certification", "Optional", "Q-Ref: Q18"),
    ("Certification", "IEEE 1547.3 Compliance Statement", "Optional", "Q-Ref: Q18"),
    ("Certification", "SOC 2 Type II Attestation Report", "Required", "Q-Ref: Q18 (obtain report)"),
    ("Company & Legal", "Vendor profile: legal name", "Required", ""),
    ("Company & Legal", "Vendor profile: address", "Required", ""),
    ("Company & Legal", "Vendor profile: all physical locations", "Required", ""),
    ("Company & Legal", "Vendor profile: website URL", "Required", ""),
    ("Company & Legal", "Vendor profile: years in business", "Required", ""),
    ("Company & Legal", "Vendor profile: annual revenue", "Required", ""),
    ("Company & Legal", "Listed States of Incorporation & Articles of Incorporation", "Required", ""),
    ("Company & Legal", "Affiliated and parent companies / cap table summary", "Required", "Q-Ref: Q30"),
    ("Company & Legal", "Officer / Director list and key personnel (KYC)", "Required", "Standard KYC"),
    ("Company & Legal", "Training (PIs) / customer service programs available?", "Required", "Q-Ref: Q25 (provide state-by-state installer coverage)"),
    ("Compliance & Risk", "Specialized / compliance certifications or licenses (company-level)", "Required", ""),
    ("Compliance & Risk", "Regulatory compliance (industry-specific)", "Required", ""),
    ("Compliance & Risk", "FEOC / PFE @ company-ownership OR product-level", "Required", "See Core Product & Compliance"),
    ("Compliance & Risk", "DCA requirements: are DCA products available?", "Required", ""),
    ("Compliance & Risk", "No history of major legal / ethical violations (attestation)", "Required", ""),
    ("Compliance & Risk", "Pending or threatened litigation disclosure", "Required", "Standard for tax equity"),
    ("Compliance & Risk", "Vendor / Supplier Code of Conduct", "Required", "Tessa action"),
    ("Compliance & Risk", "Data Security Policy (company-level)", "Required", "Q-Ref: Q18"),
    ("Supply Chain & Logistics", "Ability to handle fluctuations in demand", "Required", "Q-Ref: Q28 (lead time at sustained volume tiers)"),
    ("Supply Chain & Logistics", "Ability to scale production", "Required", "Q-Ref: Q28"),
    ("Supply Chain & Logistics", "Traceability procedures in place", "Required", "Q-Ref: Q7"),
    ("Supply Chain & Logistics", "RMA process provided", "Required", "Q-Ref: Q10 (per-component RMA pricing for CLS reserves)"),
    ("Supply Chain & Logistics", "ANSI/SEIA 101 traceability protocol attestation", "Required", "Q-Ref: Q7"),
    ("Supply Chain & Logistics", "UFLPA compliance attestation", "Required", "Q-Ref: Q7 (increasingly required by tax equity)"),
    ("Supply Chain & Logistics", "Third-party UFLPA audit reports", "Required", "Tessa action"),
    ("Supply Chain & Logistics", "Third-party manufacturing facility inspection reports", "Required", "Tessa action"),
    ("Supply Chain & Logistics", "Sustainability strategy / EPR statement", "Required", "Tessa action (RCRA & Universal Waste Rule)"),
    ("Supply Chain & Logistics", "Recycling policy (RCRA / Universal Waste Rule compliant)", "Required", "End-of-life electronics handling"),
    ("Supply Chain & Logistics", "OSHA-aligned safety policy", "Required", "Tessa action"),
    ("Financial", "Credit check / annual report (audited financials if private)", "Required", "Standard bankability check"),
    ("Financial", "Significant deals (mergers / acquisitions / spin-offs)", "Required", "Q-Ref: Q30"),
    ("Financial", "Insolvency / business continuity provisions", "Required", "Q-Ref: Q36 (cloud fallback + technology continuity)"),
    ("Financial", "Technology / source-code escrow availability", "Optional", "Q-Ref: Q36 (tail-risk for 25-yr tax equity life)"),
    ("Bankability", "Parent Co. backing report", "Required", "Q-Ref: Q30 (investor commitments)"),
    ("Insurance", "Certificate of Insurance (COI): additional insured naming (EnFin / Qcells / lessees)", "Required", "Specific entity names required; Tessa action"),
    ("Insurance", "Product liability insurance (policy & limits)", "Required", ""),
    ("Insurance", "General liability insurance (policy & limits)", "Required", ""),
    ("Insurance", "Professional liability / E&O insurance", "Required", ""),
    ("Insurance", "Cyber liability insurance (policy & limits)", "Required", "Connected-device exposure"),
    ("Warranty & Service", "Limited Warranty (USA): full terms & conditions", "Required", ""),
    ("Warranty & Service", "Support & Services Overview", "Required", ""),
    ("Warranty & Service", "Warranty labor coverage clarification (parts vs parts+labor)", "Required", "Q-Ref: Q34"),
    ("Warranty & Service", "Out-of-warranty service price schedule", "Required", "Q-Ref: Q32 (parts + labor for OPEX modeling)"),
    ("Warranty & Service", "Cellular connectivity terms / renewal pricing", "Required", "Q-Ref: Q35 (recurring OPEX item)"),
    ("Warranty & Service", "Authorized Installer training program documentation", "Required", "Installer certification process"),
    ("Warranty & Service", "Warranty financial backstop / wrap (insurance carrier)", "Required", "Q-Ref: Q12 (long-warranty counterparty risk)"),
]


# name, product category, source sheet id, items
TEMPLATES = [
    ("PV Module (DC) - AVL Requirements", "DC Module", "1-XV87S393Sf_rV7o25n3lTzs6tqXEFHzhCQF8N-xciU", PV_MODULE_DC),
    ("AC Module (P-PERC) - AVL Requirements", "AC Module", "1y2DL9iZ4B79OyogP3fYpyrLpqJPvE7ukefb3Lujpf_4", _with_notes(AC_MODULE, AC_PPERC_NOTES)),
    ("AC Module (N-TOPCon) - AVL Requirements", "AC Module", "17rhE1riqOBfJHM_MJWuuoueTMf4Wp-sX_aJLg5fYbiU", _with_notes(AC_MODULE, AC_NTOPCON_NOTES)),
    ("Inverter - AVL Requirements", "Inverter", "1CXPMN8lPpjiRD1Lj5PFGOFQAEEb-xwjH-GqhLSuRSiw", INVERTER),
    ("Microinverter / MLPE - AVL Requirements", "MLPE", "1CXPMN8lPpjiRD1Lj5PFGOFQAEEb-xwjH-GqhLSuRSiw", INVERTER),
    ("ESS / BESS - AVL Requirements", "ESS", "1bdJtXr_M5obcxvU3B9sqjWVU0VHCKqz5KPLO5jEPkX4", ESS),
    ("Smart Panel - AVL Requirements", "Smart Panel", "1--qsCJZ73fbDK687Z8c2MIp-cjqqdcwb08Qi-b16onA", SMART_PANEL),
]
